version: '3.8'

services:
  db:
    image: postgres:17.0-alpine
    container_name: postgres-db
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: carberus
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  migrate:
    image: flyway/flyway
    command: -url=jdbc:postgresql://db:5432/carberus -user=root -password=root -connectRetries=60 migrate
    environment:
      FLYWAY_URL: jdbc:postgresql://db:5432/carberus
      FLYWAY_USER: root
      FLYWAY_PASSWORD: root
    volumes:
      - ./src/main/resources/db/migrations:/flyway/sql
    depends_on:
      - db

volumes:
  postgres_data: