server:
  port: 10001

spring:
  application:
    name: carberus
  datasource:
    url: jdbc:postgresql://localhost:5432/carberus
    username: root
    password: root
    jpa:
      hibernate:
        ddl-auto: validate
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect
  
logging:
  level:
    org.springframework.security: info

